import { useState } from 'react'
import { Ban, CheckCircle2, KeyRound, Plus, Tag, Trash2, Users } from 'lucide-react'
import { sb } from '../../lib/supabase'
import OnlineNow, { OnlineDot, isOnline, loginLabel, usePresence } from './OnlineNow'
import { Alert, Avatar, Badge, Btn, EmptyState, ErrorState, Field, IconBtn, Modal, PageHeader, PageSkeleton, Pager, SearchInput, Segmented, fdt, friendly, pct, usePager, useAsync, useUi } from '../../components/ui'
export default function Students() {
  const { confirm, toast } = useUi(), seen = usePresence(), [q, setQ] = useState(''), [tab, setTab] = useState('all'), [add, setAdd] = useState(false), [pw, setPw] = useState(null), [grp, setGrp] = useState(null), [gname, setGname] = useState(''), [f, setF] = useState({ full_name: '', phone: '', password: '' }), [npw, setNpw] = useState(''), [err, setErr] = useState(''), [busy, setBusy] = useState(false)
  const { data, loading, error, reload } = useAsync(async () => {
    const [p, a] = await Promise.all([sb.from('profiles').select('*').eq('role', 'student').order('created_at', { ascending: false }), sb.from('attempts').select('student_id,score,max_score,status,submitted_at,started_at')])
    if (p.error) throw p.error
    return p.data.map(s => { const m = (a.data || []).filter(x => x.student_id === s.id), d = m.filter(x => x.status !== 'in_progress'); return { ...s, n: d.length, avg: d.length ? Math.round(d.reduce((t, x) => t + pct(x.score, x.max_score), 0) / d.length) : null, last: m.map(x => x.submitted_at || x.started_at).sort().at(-1) } }) }, [])
  const all = data || [], pend = all.filter(s => !s.active), list = all.filter(s => (tab === 'all' || (tab === 'pending' ? !s.active : s.active)) && (!q || s.full_name.includes(q) || (s.phone || '').includes(q))), pg = usePager(list, 12)
  const call = async (method, body) => { const { data: { session } } = await sb.auth.getSession(); const r = await fetch('/api/students', { method, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify(body) }); const j = await r.json().catch(() => ({})); if (!r.ok) throw new Error(j.error || 'تعذر تنفيذ العملية'); return j }
  const setActive = async (ids, active) => { const { error } = await sb.from('profiles').update({ active }).in('id', ids); error ? toast(friendly(error), 'error') : (toast(active ? 'تم تفعيل الحساب' : 'تم إيقاف الحساب'), reload()) }
  const save = async () => { setErr(''); setBusy(true); try { await call('POST', f); toast('تمت إضافة الطالب (مفعّل)'); setAdd(false); setF({ full_name: '', phone: '', password: '' }); reload() } catch (e) { setErr(friendly(e)) } setBusy(false) }
  const savePw = async () => { setErr(''); setBusy(true); try { await call('PATCH', { id: pw.id, password: npw }); toast('تم تغيير كلمة المرور'); setPw(null); setNpw('') } catch (e) { setErr(friendly(e)) } setBusy(false) }
  if (loading) return <PageSkeleton />; if (error) return <ErrorState onRetry={reload} />
  return <><PageHeader title="الطلاب" desc={`${all.length} طالب · ${pend.length} بانتظار التفعيل`}>{pend.length > 0 && <Btn variant="secondary" icon={CheckCircle2} onClick={async () => { if (await confirm('تفعيل كل الحسابات المعلّقة؟', `سيتم تفعيل ${pend.length} حساب.`, false)) setActive(pend.map(s => s.id), true) }}>تفعيل الكل</Btn>}<Btn icon={Plus} onClick={() => { setErr(''); setAdd(true) }}>إضافة طالب</Btn></PageHeader>
    {pend.length > 0 && tab !== 'pending' && <Alert tone="warning">{pend.length} حساب جديد ينتظر تفعيلك. لن يستطيع هؤلاء الطلاب الدخول إلى الواجبات قبل ذلك.</Alert>}
    <Segmented value={tab} onChange={setTab} items={[['all', 'الكل', all.length], ['pending', 'بانتظار التفعيل', pend.length], ['active', 'مفعّلون', all.length - pend.length]]} />
    <div style={{ maxWidth: 360, margin: '12px 0' }}><SearchInput value={q} onChange={setQ} placeholder="ابحث بالاسم أو رقم الهاتف" /></div>
    {!list.length ? <EmptyState icon={Users} title={q ? 'لا توجد نتائج' : tab === 'pending' ? 'لا توجد حسابات بانتظار التفعيل' : 'لا يوجد طلاب بعد'} text={q ? 'جرّب اسمًا أو رقمًا آخر.' : 'أضف طلابك من هنا، أو دعهم يسجلون بأنفسهم ثم فعّل حساباتهم.'} /> :
      <div className="tablew cards"><table><thead><tr><th>الطالب</th><th>رقم الهاتف</th><th>الحالة</th><th>الاتصال</th><th>الواجبات</th><th>المتوسط</th><th>آخر نشاط</th><th /></tr></thead><tbody>{pg.slice.map(s => <tr key={s.id}><td data-l="الطالب"><span className="row"><Avatar name={s.full_name} /><span><b>{s.full_name}</b>{s.group_name && <div><Badge>{s.group_name}</Badge></div>}</span></span></td><td data-l="الهاتف" className="ltr">{s.phone || '—'}</td>
        <td data-l="الحالة">{s.active ? <Badge tone="success">مفعّل</Badge> : <Badge tone="warning">بانتظار التفعيل</Badge>}</td><td data-l="الاتصال">{(() => { const p = seen[s.id] || s, on = p.online ?? isOnline(p); return on ? <span className="row" style={{ gap: 6 }}><OnlineDot on /><b className="small" style={{ color: 'var(--c-success)' }}>أونلاين الآن</b></span> : <span className="row" style={{ gap: 6 }}><OnlineDot /><span className="small muted">آخر دخول: {loginLabel(p)}</span></span> })()}</td><td data-l="الواجبات">{s.n}</td><td data-l="المتوسط">{s.avg != null ? <Badge tone={s.avg >= 50 ? 'success' : 'danger'}>{s.avg}%</Badge> : <span className="muted">—</span>}</td><td data-l="آخر نشاط">{s.last ? fdt(s.last) : '—'}</td>
        <td><span className="row" style={{ justifyContent: 'flex-end' }}>{s.active ? <IconBtn icon={Ban} label={`إيقاف حساب ${s.full_name}`} onClick={async () => { if (await confirm('إيقاف الحساب؟', `لن يستطيع ${s.full_name} الدخول حتى تعيد تفعيله.`)) setActive([s.id], false) }} /> : <Btn size="sm" variant="success" icon={CheckCircle2} onClick={() => setActive([s.id], true)}>تفعيل</Btn>}
          <IconBtn icon={Tag} label={`تعيين مجموعة لـ ${s.full_name}`} onClick={() => { setGname(s.group_name || ''); setGrp(s) }} />
          <IconBtn icon={KeyRound} label={`تغيير كلمة مرور ${s.full_name}`} onClick={() => { setErr(''); setNpw(''); setPw(s) }} />
          <IconBtn icon={Trash2} label={`حذف ${s.full_name}`} onClick={async () => { if (await confirm('حذف الطالب؟', `سيُحذف ${s.full_name} وكل نتائجه نهائيًا.`)) try { await call('DELETE', { id: s.id }); toast('تم حذف الطالب'); reload() } catch (e) { toast(friendly(e), 'error') } }} /></span></td></tr>)}</tbody></table></div>}
    <Pager pg={pg} total={list.length} />
    {add && <Modal title="إضافة طالب" desc="الطالب الذي تضيفه بنفسك يكون مفعّلًا مباشرة." onClose={() => setAdd(false)} footer={<><Btn variant="secondary" onClick={() => setAdd(false)}>إلغاء</Btn><Btn disabled={busy || !f.full_name || !f.phone || f.password.length < 6} onClick={save}>{busy ? 'جارٍ الإضافة…' : 'إضافة الطالب'}</Btn></>}>
      <Alert>{err}</Alert><Field label="الاسم"><input value={f.full_name} onChange={e => setF({ ...f, full_name: e.target.value })} /></Field><Field label="رقم الهاتف" hint="يستخدمه الطالب لتسجيل الدخول"><input dir="ltr" inputMode="tel" value={f.phone} onChange={e => setF({ ...f, phone: e.target.value })} /></Field><Field label="كلمة المرور" hint="6 أحرف على الأقل"><input dir="ltr" value={f.password} onChange={e => setF({ ...f, password: e.target.value })} /></Field></Modal>}
    {grp && <Modal title="مجموعة الطالب" desc={grp.full_name} onClose={() => setGrp(null)} footer={<><Btn variant="secondary" onClick={() => setGrp(null)}>إلغاء</Btn><Btn onClick={async () => { const { error } = await sb.from('profiles').update({ group_name: gname.trim() || null }).eq('id', grp.id); error ? toast(friendly(error), 'error') : (toast('تم حفظ المجموعة'), setGrp(null), reload()) }}>حفظ</Btn></>}><Field label="اسم المجموعة" hint="مثال: مجموعة السبت. اتركه فارغًا لإزالة الطالب من مجموعته. تُستخدم لاستهداف الإعلانات."><input list="groups" autoFocus value={gname} onChange={e => setGname(e.target.value)} /><datalist id="groups">{[...new Set(all.map(x => x.group_name).filter(Boolean))].map(g => <option key={g} value={g} />)}</datalist></Field></Modal>}
    {pw && <Modal title="تغيير كلمة المرور" desc={pw.full_name} onClose={() => setPw(null)} footer={<><Btn variant="secondary" onClick={() => setPw(null)}>إلغاء</Btn><Btn disabled={busy || npw.length < 6} onClick={savePw}>{busy ? 'جارٍ الحفظ…' : 'حفظ كلمة المرور'}</Btn></>}><Alert>{err}</Alert><Field label="كلمة المرور الجديدة" hint="6 أحرف على الأقل. أبلغ الطالب بها بنفسك."><input dir="ltr" autoFocus value={npw} onChange={e => setNpw(e.target.value)} /></Field></Modal>}</>
}
